"""empty message

Revision ID: 1a4e9b644d60
Revises: 899381491e4d
Create Date: 2025-05-18 10:27:44.240724

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a4e9b644d60'
down_revision = '899381491e4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app', schema=None) as batch_op:
        batch_op.drop_column('flag')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app', schema=None) as batch_op:
        batch_op.add_column(sa.Column('flag', sa.SMALLINT(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
